# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            SAGE
tagline:          'SAGE'
description:      'The Student Assembly for Gender Empowerment at the University of Southern California'
url:              https://sageusc.github.io
baseurl:         https://sageusc.github.io/

author:
  name:           'SAGE'
  url:            https://twitter.com/sageusc

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
